# Generated by Django 5.2.6 on 2025-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('online', 'آنلاین'), ('cash', 'نقدی')], default='online', max_length=100),
        ),
    ]
