# Generated by Django 5.2.6 on 2025-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
